// 生成器：读取 src/data/bulk-*.csv → 去重 → 生成 src/data/seed-bulk.ts
// 分块输出（每块 ≤300 条），避免 TS2590「联合类型过复杂」。
// 用法：node scripts/build-seed.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'src', 'data');
const OUT = join(DATA_DIR, 'seed-bulk.ts');

const VALID_BANDS = new Set(['5', '6', '7', '8']);
const CHUNK = 300;

const files = readdirSync(DATA_DIR)
  .filter((f) => /^bulk-.*\.csv$/i.test(f))
  .sort();

if (files.length === 0) {
  console.error('未找到 bulk-*.csv');
  process.exit(1);
}

const seen = new Set();
const entries = [];
let skipped = 0;
let dup = 0;

for (const file of files) {
  const raw = readFileSync(join(DATA_DIR, file), 'utf8');
  for (const line of raw.split(/\r?\n/)) {
    const t = line.trim();
    if (!t) continue;
    const i1 = t.indexOf(',');
    const i2 = t.lastIndexOf(',');
    if (i1 === -1 || i2 === -1 || i1 === i2) {
      skipped++;
      continue;
    }
    const term = t.slice(0, i1).trim();
    const band = t.slice(i2 + 1).trim();
    const meaningZh = t.slice(i1 + 1, i2).trim();
    if (!term || !meaningZh || !VALID_BANDS.has(band)) {
      skipped++;
      continue;
    }
    const key = term.toLowerCase();
    if (seen.has(key)) {
      dup++;
      continue;
    }
    seen.add(key);
    entries.push({ term, meaningZh, band });
  }
}

// 先按全局序号分配 id，再分块
const rowOf = (e, idx) =>
  `  { id: "bulk-${idx + 1}", term: ${JSON.stringify(e.term)}, phonetic: '', pos: '', ` +
  `meaningZh: ${JSON.stringify(e.meaningZh)}, meaningEn: '', band: ${JSON.stringify(e.band)}, ` +
  `collocations: [], example: '', exampleZh: '' }`;

const chunks = [];
for (let i = 0; i < entries.length; i += CHUNK) {
  chunks.push(entries.slice(i, i + CHUNK));
}

const partDecls = chunks
  .map((c, ci) => {
    const rows = c.map((e, j) => rowOf(e, ci * CHUNK + j)).join(',\n');
    return `const part_${ci + 1}: VocabEntry[] = [\n${rows}\n];`;
  })
  .join('\n\n');

const combine =
  `export const SEED_BULK: VocabEntry[] = [\n${chunks
    .map((_, ci) => `  ...part_${ci + 1}`)
    .join(',\n')}\n];`;

const header =
  `// AUTO-GENERATED by scripts/build-seed.mjs — 请勿手改。\n` +
  `// 源数据见 src/data/bulk-*.csv（term, 中文释义, band）。分块以避免 TS2590。\n` +
  `import type { VocabEntry } from './words';\n\n`;

writeFileSync(OUT, header + partDecls + '\n\n' + combine + '\n', 'utf8');

const byBand = { '5': 0, '6': 0, '7': 0, '8': 0 };
for (const e of entries) byBand[e.band]++;
console.log(`已生成 ${entries.length} 条（分 ${chunks.length} 块）→ ${OUT}`);
console.log(`分档: Band5=${byBand['5']} Band6=${byBand['6']} Band7=${byBand['7']} Band8=${byBand['8']}`);
console.log(`跳过(格式/非法): ${skipped}  重复term跳过: ${dup}`);
