// 生成器：读取 src/data/bulk-*.csv → 去重 → 生成 src/data/seed-bulk.ts
// 分块输出（每块 ≤300 条），避免 TS2590「联合类型过复杂」。
//
// 支持两种列格式（都带表头行）：
//   旧 3 列： term,meaningZh,band
//   新 7 列： term,pos,meaningZh,meaningEn,exampleEn,exampleZh,band
// 缺字段补空字符串；term 不区分大小写去重。
//
// 用法：node scripts/build-seed.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import Papa from 'papaparse';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'src', 'data');
const OUT = join(DATA_DIR, 'seed-bulk.ts');

const VALID_BANDS = new Set(['5', '6', '7', '8', '9']);
const CHUNK = 300;

const files = readdirSync(DATA_DIR)
  .filter((f) => /^bulk-.*\.csv$/i.test(f))
  .sort();

if (files.length === 0) {
  console.error('未找到 bulk-*.csv');
  process.exit(1);
}

// 按「档内」去重：允许同一单词出现在不同 band（学习时可按档重复巩固），
// 但同一档内不重复。这样每一档都能保留完整词量，满足「各档 ~500 词」的需求。
const seenByBand = {};
const entries = [];
let skipped = 0;
let dup = 0;

for (const file of files) {
  const raw = readFileSync(join(DATA_DIR, file), 'utf8');
  const parsed = Papa.parse(raw.trim(), {
    header: false,
    skipEmptyLines: true,
  });
  const rows = parsed.data;
  let start = 0;
  // 首行若是表头（含 term/band 字样）则跳过，兼容「无表头旧 3 列」与「带表头富文本」。
  if (rows.length > 0) {
    const first = (rows[0] || []).map((c) => String(c).trim().toLowerCase());
    if (first.includes('term') && first.includes('band')) start = 1;
  }
  for (let r = start; r < rows.length; r++) {
    const cells = (rows[r] || []).map((c) => String(c).trim());
    if (cells.length < 3) {
      skipped++;
      continue;
    }
    // 旧 3 列：term,meaningZh,band；富文本 7 列：term,pos,meaningZh,meaningEn,exampleEn,exampleZh,band
    const isEnriched = cells.length >= 7;
    const term = cells[0];
    const band = isEnriched ? cells[6] : cells[cells.length - 1];
    const meaningZh = isEnriched ? cells[2] : cells[1];
    if (!term || !meaningZh || !VALID_BANDS.has(band)) {
      skipped++;
      continue;
    }
    const key = term.toLowerCase();
    const bset = seenByBand[band] || (seenByBand[band] = new Set());
    if (bset.has(key)) {
      dup++;
      continue;
    }
    bset.add(key);
    entries.push({
      term,
      band,
      pos: isEnriched ? cells[1] : '',
      meaningZh,
      meaningEn: isEnriched ? cells[3] : '',
      exampleEn: isEnriched ? cells[4] : '',
      exampleZh: isEnriched ? cells[5] : '',
    });
  }
}

// 先按全局序号分配 id，再分块（避免 TS2590）。
const rowOf = (e, idx) =>
  `  { id: "bulk-${idx + 1}", term: ${JSON.stringify(e.term)}, phonetic: '', ` +
  `pos: ${JSON.stringify(e.pos)}, meaningZh: ${JSON.stringify(e.meaningZh)}, ` +
  `meaningEn: ${JSON.stringify(e.meaningEn)}, band: ${JSON.stringify(e.band)}, ` +
  `collocations: [], example: ${JSON.stringify(e.exampleEn)}, exampleZh: ${JSON.stringify(e.exampleZh)} }`;

const chunks = [];
for (let i = 0; i < entries.length; i += CHUNK) {
  chunks.push(entries.slice(i, i + CHUNK));
}

const partDecls = chunks
  .map((c, ci) => {
    const rows = c.map((e, j) => rowOf(e, ci * CHUNK + j)).join(',\n');
    return `const part_${ci + 1}: VocabEntry[] = [\n${rows}\n];`;
  })
  .join('\n\n');

const combine =
  `export const SEED_BULK: VocabEntry[] = [\n${chunks
    .map((_, ci) => `  ...part_${ci + 1}`)
    .join(',\n')}\n];`;

const header =
  `// AUTO-GENERATED by scripts/build-seed.mjs — 请勿手改。\n` +
  `// 源数据见 src/data/bulk-*.csv（带表头；3 列旧格式或 7 列富文本）。分块以避免 TS2590。\n` +
  `import type { VocabEntry } from './words';\n\n`;

writeFileSync(OUT, header + partDecls + '\n\n' + combine + '\n', 'utf8');

const byBand = { '5': 0, '6': 0, '7': 0, '8': 0, '9': 0 };
for (const e of entries) byBand[e.band]++;
console.log(`已生成 ${entries.length} 条（分 ${chunks.length} 块）→ ${OUT}`);
console.log(`分档: Band5=${byBand['5']} Band6=${byBand['6']} Band7=${byBand['7']} Band8=${byBand['8']} Band9=${byBand['9']}`);
console.log(`跳过(格式/非法): ${skipped}  重复term跳过: ${dup}`);
