// 临时脚本：向 bulk-band9.csv 追加约 100 条 GRE/高级词（7 列富文本，band=9）
import { readFileSync, appendFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const P = join(__dirname, '..', 'src', 'data', 'bulk-band9.csv');

// [term, pos, meaningZh, meaningEn, exampleEn, exampleZh]
const extra = [
  ['abstinence', 'n.', '节制；禁戒', 'restraint from indulgence', 'He practiced abstinence from alcohol.', '他戒酒了。', '9'],
  ['acrimony', 'n.', '尖刻；刻薄', 'bitter anger', 'The debate was full of acrimony.', '辩论充满了尖刻。', '9'],
  ['acumen', 'n.', '敏锐；洞察力', 'sharp insight', 'She has business acumen.', '她有商业洞察力。', '9'],
  ['adage', 'n.', '格言；谚语', 'a wise saying', 'An old adage guided him.', '一句古老的格言指引了他。', '9'],
  ['adversity', 'n.', '逆境；不幸', 'hard fortune', 'He thrived in adversity.', '他在逆境中成长。', '9'],
  ['affluent', 'adj.', '富裕的', 'wealthy', 'They live in an affluent area.', '他们住在富裕区。', '9'],
  ['agitate', 'v.', '煽动；搅动', 'to stir up', 'They agitated for change.', '他们鼓动变革。', '9'],
  ['alchemy', 'n.', '炼金术', 'medieval chemistry', 'Alchemy sought gold.', '炼金术追求黄金。', '9'],
  ['allay', 'v.', '减轻；平息', 'to calm', 'The news allayed fears.', '消息平息了恐惧。', '9'],
  ['ambrosial', 'adj.', '芳香的；美味的', 'fragrant', 'The ambrosial meal delighted them.', '那顿美餐让他们愉悦。', '9'],
  ['amorphous', 'adj.', '无定形的', 'shapeless', 'The plan was amorphous.', '计划模糊不清。', '9'],
  ['antithesis', 'n.', '对立面', 'direct opposite', 'His view is the antithesis of mine.', '他的观点与我的正相反。', '9'],
  ['apogee', 'n.', '最高点', 'highest point', 'The rocket reached its apogee.', '火箭到达了最高点。', '9'],
  ['approbation', 'n.', '认可；赞许', 'approval', 'He won their approbation.', '他赢得了赞许。', '9'],
  ['arcane', 'adj.', '神秘的', 'secret', 'The rite was arcane.', '仪式很神秘。', '9'],
  ['ardor', 'n.', '热情', 'passion', 'She argued with ardor.', '她热情地辩论。', '9'],
  ['ascendancy', 'n.', '优势；支配', 'dominance', 'They gained ascendancy.', '他们取得了优势。', '9'],
  ['avow', 'v.', '公开承认', 'to declare', 'He avowed his belief.', '他公开承认了信念。', '9'],
  ['banal', 'adj.', '平庸的', 'trite', 'The comment was banal.', '这评论很平庸。', '9'],
  ['beatitude', 'n.', '极乐', 'blessedness', 'He spoke of beatitude.', '他谈到了极乐。', '9'],
  ['bedlam', 'n.', '混乱', 'uproar', 'The room was bedlam.', '房间里一片混乱。', '9'],
  ['belie', 'v.', '掩饰；与…不符', 'to contradict', 'His smile belied his fear.', '他的微笑掩饰了恐惧。', '9'],
  ['benign', 'adj.', '良性的；温和的', 'harmless', 'The tumor was benign.', '肿瘤是良性的。', '9'],
  ['bombast', 'n.', '浮夸的言辞', 'pompous speech', 'His bombast bored them.', '他的浮夸令人厌烦。', '9'],
  ['burgeon', 'v.', '迅速发展', 'to grow fast', 'The city burgeoned.', '城市迅速发展。', '9'],
  ['cajole', 'v.', '哄骗；劝诱', 'to coax', 'She cajoled him into going.', '她哄他一起去。', '9'],
  ['calumny', 'n.', '诽谤', 'false accusation', 'He sued over calumny.', '他因诽谤起诉。', '9'],
  ['camaraderie', 'n.', '同志情谊', 'good fellowship', 'The team shared camaraderie.', '团队情谊深厚。', '9'],
  ['candor', 'n.', '坦率', 'honesty', 'She spoke with candor.', '她坦率地说。', '9'],
  ['caprice', 'n.', '任性；突发奇想', 'whim', 'He acted on a caprice.', '他凭一时冲动行事。', '9'],
  ['castigate', 'v.', '严厉批评', 'to rebuke', 'The critic castigated the film.', '评论家严厉批评了影片。', '9'],
  ['catholic', 'adj.', '广泛的；普遍的', 'broad', 'He has catholic tastes.', '他兴趣广泛。', '9'],
  ['caustic', 'adj.', '尖酸刻薄的', 'biting', 'Her caustic remark stung.', '她刻薄的话刺痛了人。', '9'],
  ['censure', 'v.', '谴责', 'to criticize', 'The board censured him.', '董事会谴责了他。', '9'],
  ['chicanery', 'n.', '诡计', 'trickery', 'The deal involved chicanery.', '交易里有诡计。', '9'],
  ['chimerical', 'adj.', '空想的', 'fantastic', 'The plan was chimerical.', '计划不切实际。', '9'],
  ['circumspect', 'adj.', '谨慎的', 'cautious', 'He was circumspect.', '他十分谨慎。', '9'],
  ['clamor', 'n./v.', '喧闹；大声要求', 'loud noise', 'The crowd clamored for justice.', '人群大声要求公正。', '9'],
  ['cleave', 'v.', '劈开；粘着', 'to split', 'He cleaved the log.', '他劈开了木头。', '9'],
  ['cloying', 'adj.', '过甜的；腻人的', 'too sweet', 'The cloying dessert sickened her.', '甜腻的甜点让她反胃。', '9'],
  ['coeval', 'adj.', '同时代的', 'of the same age', 'The two were coeval.', '两者属于同一时代。', '9'],
  ['cogitate', 'v.', '深思', 'to ponder', 'He cogitated the problem.', '他深思这个问题。', '9'],
  ['comeliness', 'n.', '美丽；优雅', 'beauty', 'Her comeliness drew looks.', '她的美貌引人注目。', '9'],
  ['concatenate', 'v.', '连接；串联', 'to link', 'We concatenated the files.', '我们串联了文件。', '9'],
  ['concomitant', 'adj.', '伴随的', 'accompanying', 'Poverty is a concomitant of war.', '贫困是战争的伴随物。', '9'],
  ['condone', 'v.', '宽恕；纵容', 'to overlook', 'We cannot condone cheating.', '我们不能纵容作弊。', '9'],
  ['confluence', 'n.', '汇聚', 'flowing together', 'A confluence of rivers met.', '多条河流汇聚。', '9'],
  ['connoisseur', 'n.', '鉴赏家', 'expert judge', 'He is a wine connoisseur.', '他是葡萄酒鉴赏家。', '9'],
  ['contumely', 'n.', '傲慢无礼', 'insolent abuse', 'He endured contumely.', '他忍受了侮辱。', '9'],
  ['corollary', 'n.', '推论', 'natural consequence', 'This is a corollary of the law.', '这是该定律的推论。', '9'],
  ['countenance', 'n./v.', '面容；支持', 'face or support', 'He countenanced the plan.', '他支持这个计划。', '9'],
  ['cupidity', 'n.', '贪婪', 'greed', 'Cupidity drove him.', '贪婪驱使他。', '9'],
  ['deleterious', 'adj.', '有害的', 'harmful', 'The effect was deleterious.', '影响是有害的。', '9'],
  ['demagogue', 'n.', '煽动者', 'rabble rouser', 'The demagogue stirred crowds.', '煽动者挑动了人群。', '9'],
  ['denouement', 'n.', '结局', 'final outcome', 'The denouement surprised all.', '结局让所有人惊讶。', '9'],
  ['depredation', 'n.', '掠夺', 'plundering', 'War brought depredation.', '战争带来了掠夺。', '9'],
  ['desiccate', 'v.', '使干燥', 'to dry out', 'The sun desiccated the land.', '太阳晒干了土地。', '9'],
  ['diaphanous', 'adj.', '透明的；精致的', 'sheer', 'She wore a diaphanous gown.', '她穿着透明的长袍。', '9'],
  ['didactic', 'adj.', '说教的', 'intended to teach', 'The book was didactic.', '这本书有说教意味。', '9'],
  ['disabuse', 'v.', '使醒悟', 'to free from error', 'He disabused her of the myth.', '他让她摆脱了误解。', '9'],
  ['discomfit', 'v.', '使困惑；使尴尬', 'to unsettle', 'The question discomfited him.', '这个问题让他尴尬。', '9'],
  ['dissemble', 'v.', '掩饰', 'to pretend', 'He dissembled his grief.', '他掩饰了悲伤。', '9'],
  ['distaff', 'n./adj.', '女性（的）', 'female side', 'The distaff side of the family.', '家族的女性一方。', '9'],
  ['droll', 'adj.', '滑稽的', 'amusing', 'His droll tale amused them.', '他滑稽的故事逗乐了大家。', '9'],
  ['ebullient', 'adj.', '热情奔放的', 'exuberant', 'She was ebullient.', '她热情奔放。', '9'],
  ['edify', 'v.', '启发；教化', 'to instruct', 'The sermon edified them.', '布道启发了他们。', '9'],
  ['effulgent', 'adj.', '光辉的', 'radiant', 'The effulgent sun rose.', '灿烂的太阳升起了。', '9'],
  ['egregious', 'adj.', '极坏的', 'outstandingly bad', 'An egregious error occurred.', '出现了严重的错误。', '9'],
  ['elucidate', 'v.', '阐明', 'to explain', 'He elucidated the point.', '他阐明了要点。', '9'],
  ['emolument', 'n.', '报酬', 'payment', 'The emolument was fair.', '报酬很合理。', '9'],
  ['encomium', 'n.', '赞颂', 'formal praise', 'He delivered an encomium.', '他致了颂词。', '9'],
  ['enfranchise', 'v.', '授予权利', 'to give rights', 'The law enfranchised women.', '法律赋予女性权利。', '9'],
  ['epitome', 'n.', '典范；缩影', 'perfect example', 'He is the epitome of grace.', '他是优雅的典范。', '9'],
  ['equivocate', 'v.', '含糊其辞', 'to be ambiguous', 'He equivocated on the issue.', '他在问题上含糊其辞。', '9'],
  ['erudite', 'adj.', '博学的', 'learned', 'She is erudite.', '她博学多才。', '9'],
  ['eschew', 'v.', '避开；戒绝', 'to avoid', 'He eschewed conflict.', '他避开了冲突。', '9'],
  ['evanescent', 'adj.', '短暂的', 'fading', 'The evanescent mist cleared.', '短暂的雾散去了。', '9'],
  ['excoriate', 'v.', '严厉指责', 'to censure', 'They excoriated the policy.', '他们严厉批评了政策。', '9'],
  ['exigency', 'n.', '紧急需要', 'urgency', 'The exigency required speed.', '紧急情况需要速度。', '9'],
  ['expiate', 'v.', '赎罪', 'to atone', 'He sought to expiate his sin.', '他试图赎罪。', '9'],
  ['extant', 'adj.', '现存的', 'still existing', 'Few copies are extant.', '现存副本很少。', '9'],
  ['extirpate', 'v.', '根除', 'to destroy', 'They extirpated the weed.', '他们根除了杂草。', '9'],
  ['facetious', 'adj.', '爱开玩笑的', 'joking', 'His facetious tone annoyed her.', '他开玩笑的语气惹恼了她。', '9'],
  ['fallacious', 'adj.', '谬误的', 'false', 'The argument was fallacious.', '论点有误。', '9'],
  ['fatuous', 'adj.', '愚昧的', 'foolish', 'His fatuous grin annoyed them.', '他愚蠢的傻笑惹人烦。', '9'],
  ['feckless', 'adj.', '无用的', 'ineffective', 'He was feckless at work.', '他工作不力。', '9'],
  ['felicitous', 'adj.', '恰当的', 'apt', 'Her felicitous remark helped.', '她恰当的话起了作用。', '9'],
  ['flagrant', 'adj.', '公然的', 'obvious', 'A flagrant violation occurred.', '发生了公然的违规。', '9'],
  ['foible', 'n.', '小缺点', 'minor flaw', 'His foible was lateness.', '他的小缺点是迟到。', '9'],
  ['foment', 'v.', '煽动', 'to stir up', 'He fomented revolt.', '他煽动叛乱。', '9'],
  ['fulsome', 'adj.', '过度的；令人反感的', 'excessive', 'His fulsome praise rang false.', '他过度的赞美显得虚伪。', '9'],
  ['garrulous', 'adj.', '喋喋不休的', 'talkative', 'The garrulous guest talked on.', '喋喋不休的客人说个不停。', '9'],
  ['gesticulate', 'v.', '做手势', 'to gesture', 'He gesticulated wildly.', '他疯狂地比划。', '9'],
  ['grandiloquent', 'adj.', '夸张的', 'pompous', 'His grandiloquent speech bored them.', '他夸张的演讲令人厌烦。', '9'],
  ['halcyon', 'adj.', '平静的；美好的', 'peaceful', 'They recalled halcyon days.', '他们回忆起平静的往日。', '9'],
  ['harangue', 'n./v.', '长篇训斥', 'tyrade', 'He delivered a harangue.', '他发表了一通训斥。', '9'],
  ['hegemony', 'n.', '霸权', 'dominance', 'The nation sought hegemony.', '该国谋求霸权。', '9'],
  ['hermetic', 'adj.', '密封的；深奥的', 'sealed', 'The jar was hermetic.', '罐子密封着。', '9'],
  ['hiatus', 'n.', '间断', 'gap', 'A hiatus occurred in work.', '工作中出现了间断。', '9'],
  ['hubris', 'n.', '傲慢', 'excessive pride', 'His hubris caused his fall.', '傲慢导致了他的覆灭。', '9'],
  ['immutable', 'adj.', '不可变的', 'unchanging', 'The law is immutable.', '定律不可改变。', '9'],
  ['impassive', 'adj.', '无动于衷的', 'unemotional', 'He remained impassive.', '他保持冷漠。', '9'],
  ['impecunious', 'adj.', '贫穷的', 'poor', 'The impecunious student worked.', '贫穷的学生打工。', '9'],
  ['implacable', 'adj.', '无法平息的', 'unyielding', 'His implacable foe persisted.', '他无法和解的敌人坚持着。', '9'],
  ['inchoate', 'adj.', '初步的；未成形的', 'just begun', 'The inchoate plan failed.', '初步的计划失败了。', '9'],
  ['inculcate', 'v.', '反复灌输', 'to instill', 'They inculcated values.', '他们灌输了价值观。', '9'],
  ['ineffable', 'adj.', '难以言喻的', 'indescribable', 'The view was ineffable.', '景色难以形容。', '9'],
  ['insidious', 'adj.', '隐蔽有害的', 'treacherous', 'The insidious disease spread.', '潜伏的疾病蔓延了。', '9'],
  ['internecine', 'adj.', '内部厮杀的', 'mutually destructive', 'The internecine feud ended.', '内部仇杀结束了。', '9'],
  ['inveterate', 'adj.', '根深蒂固的', 'habitual', 'He was an inveterate liar.', '他是惯于说谎的人。', '9'],
  ['jejune', 'adj.', '枯燥的；幼稚的', 'dull', 'The jejune talk bored them.', '枯燥的谈话令人生厌。', '9'],
  ['kudos', 'n.', '荣誉', 'praise', 'He earned kudos.', '他赢得了荣誉。', '9'],
  ['lambast', 'v.', '严厉批评', 'to attack', 'They lambasted the plan.', '他们猛烈批评了计划。', '9'],
  ['loquacious', 'adj.', '健谈的', 'talkative', 'The loquacious host charmed all.', '健谈的主人迷住了所有人。', '9'],
  ['lugubrious', 'adj.', '哀伤的', 'mournful', 'His lugubrious face saddened them.', '他哀伤的脸让大家难过。', '9'],
  ['magnanimous', 'adj.', '宽宏大量的', 'generous', 'He was magnanimous in victory.', '他胜得宽宏大量。', '9'],
  ['malediction', 'n.', '诅咒', 'curse', 'He uttered a malediction.', '他发出了诅咒。', '9'],
  ['malinger', 'v.', '装病', 'to feign illness', 'He malingered to avoid work.', '他装病逃避工作。', '9'],
  ['mellifluous', 'adj.', '悦耳的', 'sweet sounding', 'Her mellifluous voice soothed them.', '她悦耳的声音安抚了大家。', '9'],
  ['mendacious', 'adj.', '虚假的', 'lying', 'His mendacious tale fooled none.', '他虚假的故事骗不了人。', '9'],
  ['meretricious', 'adj.', '华而不实的', 'gaudy', 'The meretricious show failed.', '华而不实的表演失败了。', '9'],
  ['minatory', 'adj.', '威胁的', 'threatening', 'His minatory tone warned them.', '他威胁的语气警告了他们。', '9'],
  ['mitigate', 'v.', '减轻', 'to lessen', 'The law mitigated harm.', '法律减轻了伤害。', '9'],
  ['munificent', 'adj.', '慷慨的', 'very generous', 'The munificent gift helped.', '慷慨的馈赠帮了忙。', '9'],
  ['nefarious', 'adj.', '邪恶的', 'wicked', 'The nefarious plot failed.', '邪恶的阴谋失败了。', '9'],
  ['obdurate', 'adj.', '固执的', 'stubborn', 'He was obdurate.', '他固执己见。', '9'],
  ['obsequious', 'adj.', '谄媚的', 'fawning', 'His obsequious manner repelled her.', '他谄媚的态度令她反感。', '9'],
  ['obviate', 'v.', '排除；避免', 'to prevent', 'The step obviated risk.', '这一步避免了风险。', '9'],
  ['oleaginous', 'adj.', '油滑的；奉承的', 'oily', 'His oleaginous praise rang false.', '他油滑的赞美显虚伪。', '9'],
  ['palliate', 'v.', '减轻；掩饰', 'to ease', 'The drug palliated pain.', '药物减轻了疼痛。', '9'],
  ['panegyric', 'n.', '颂词', 'formal praise', 'He wrote a panegyric.', '他写了一篇颂词。', '9'],
  ['parsimonious', 'adj.', '吝啬的', 'stingy', 'The parsimonious man saved much.', '吝啬的人存了很多钱。', '9'],
  ['pedantic', 'adj.', '学究气的', 'overly precise', 'His pedantic style bored them.', '他学究式的风格令人厌烦。', '9'],
  ['pellucid', 'adj.', '透明的；清晰的', 'clear', 'The pellucid water shone.', '清澈的水闪闪发光。', '9'],
  ['penurious', 'adj.', '贫困的；吝啬的', 'poor', 'The penurious family struggled.', '贫困的家庭苦苦支撑。', '9'],
  ['peregrination', 'n.', '旅行', 'travel', 'His peregrination taught him much.', '他的旅行让他学到很多。', '9'],
  ['perfidy', 'n.', '背叛', 'treachery', 'His perfidy shocked friends.', '他的背叛震惊了朋友。', '9'],
  ['peripatetic', 'adj.', '巡回的', 'traveling', 'The peripatetic teacher moved often.', '巡回的老师经常搬家。', '9'],
  ['pernicious', 'adj.', '有害的', 'harmful', 'The pernicious habit spread.', '有害的习惯蔓延了。', '9'],
  ['perspicacious', 'adj.', '敏锐的', 'astute', 'Her perspicacious insight helped.', '她敏锐的洞察帮了忙。', '9'],
  ['petrous', 'adj.', '岩石的；坚硬的', 'rocky', 'The petrous cliff loomed.', '坚硬的悬崖耸立。', '9'],
  ['philistine', 'n./adj.', '庸人；平庸的', 'anti-art person', 'The philistine ignored art.', '庸人无视艺术。', '9'],
  ['picayune', 'adj.', '琐碎的；微小的', 'petty', 'The picayune detail annoyed him.', '琐碎的细节惹恼了他。', '9'],
  ['platitude', 'n.', '陈词滥调', 'trite remark', 'His speech was full of platitudes.', '他的演讲满是陈词滥调。', '9'],
  ['plethora', 'n.', '过多', 'excess', 'A plethora of options confused him.', '过多的选择让他困惑。', '9'],
  ['poltroon', 'n.', '懦夫', 'coward', 'The poltroon fled.', '懦夫逃跑了。', '9'],
  ['prate', 'v.', '闲聊；空谈', 'to chatter', 'He prated of his deeds.', '他空谈自己的事迹。', '9'],
  ['proclivity', 'n.', '倾向', 'inclination', 'He has a proclivity for risk.', '他有冒险倾向。', '9'],
  ['prodigal', 'adj.', '挥霍的', 'wasteful', 'The prodigal son returned.', '挥霍的儿子回来了。', '9'],
  ['profuse', 'adj.', '大量的', 'abundant', 'He gave profuse thanks.', '他连连致谢。', '9'],
  ['prolix', 'adj.', '冗长的', 'wordy', 'The prolix letter bored her.', '冗长的信让她厌烦。', '9'],
  ['propitiate', 'v.', '抚慰', 'to appease', 'They sought to propitiate the gods.', '他们试图抚慰神明。', '9'],
  ['pulchritude', 'n.', '美丽', 'beauty', 'Her pulchritude amazed all.', '她的美丽惊艳了众人。', '9'],
  ['pusillanimous', 'adj.', '怯懦的', 'cowardly', 'The pusillanimous leader hid.', '怯懦的领导躲了起来。', '9'],
  ['querulous', 'adj.', '抱怨的', 'complaining', 'The querulous guest whined.', '爱抱怨的客人发牢骚。', '9'],
  ['quixotic', 'adj.', '不切实际的', 'impractical', 'His quixotic plan failed.', '他不切实际的计划失败了。', '9'],
  ['raffish', 'adj.', '放荡的', 'disreputable', 'The raffish crowd gathered.', '放荡的人群聚在一起。', '9'],
  ['recalcitrant', 'adj.', '倔强的', 'stubborn', 'The recalcitrant mule refused.', '倔强的骡子不肯动。', '9'],
  ['redolent', 'adj.', '芬芳的；使人联想的', 'fragrant', 'The air was redolent of pine.', '空气中弥漫着松香。', '9'],
  ['refulgent', 'adj.', '辉煌的', 'shining', 'The refulgent dawn broke.', '辉煌的黎明降临。', '9'],
  ['renegade', 'n.', '叛徒', 'traitor', 'The renegade fled the camp.', '叛徒逃离了营地。', '9'],
  ['reprobate', 'n.', '堕落者', 'villain', 'The reprobate was shunned.', '堕落者被人回避。', '9'],
  ['reticent', 'adj.', '沉默寡言的', 'reserved', 'He was reticent about his past.', '他对过去保持沉默。', '9'],
  ['sanguine', 'adj.', '乐观的；面色红润的', 'optimistic', 'She was sanguine about the future.', '她对未来很乐观。', '9'],
  ['sapient', 'adj.', '睿智的', 'wise', 'The sapient elder spoke.', '睿智的长者发言了。', '9'],
  ['saturnine', 'adj.', '阴沉的', 'gloomy', 'His saturnine mood silenced them.', '他阴沉的情绪让大家安静。', '9'],
  ['scurrilous', 'adj.', '粗俗诽谤的', 'abusive', 'The scurrilous rumor spread.', '恶毒的谣言传开了。', '9'],
  ['sententious', 'adj.', '说教式的', 'moralizing', 'His sententious tone annoyed them.', '他说教式的语气惹人烦。', '9'],
  ['splenetic', 'adj.', '脾气坏的', 'irritable', 'The splenetic man snapped.', '脾气坏的人发了火。', '9'],
  ['stultify', 'v.', '使变得无效', 'to hinder', 'The rule stultified progress.', '规定阻碍了进步。', '9'],
  ['sycophant', 'n.', '阿谀奉承者', 'flatterer', 'The sycophant praised the boss.', '马屁精吹捧老板。', '9'],
  ['taciturn', 'adj.', '沉默的', 'quiet', 'The taciturn man spoke little.', '沉默的人很少说话。', '9'],
  ['titanic', 'adj.', '巨大的', 'huge', 'The titanic wave crashed.', '巨大的海浪拍下。', '9'],
  ['toady', 'n./v.', '谄媚者；奉承', 'sycophant', 'The toady flattered the king.', '谄媚者奉承国王。', '9'],
  ['truculent', 'adj.', '好斗的', 'aggressive', 'His truculent reply shocked her.', '他好斗的回答震惊了她。', '9'],
  ['ubiquitous', 'adj.', '无处不在的', 'everywhere', 'The brand is ubiquitous.', '这个品牌无处不在。', '9'],
  ['unctuous', 'adj.', '油腻的；奉承的', 'oily', 'His unctuous praise repelled her.', '他油腻的赞美令人反感。', '9'],
  ['untoward', 'adj.', '不利的；不当的', 'unfortunate', 'An untoward event occurred.', '发生了一件不幸的事。', '9'],
  ['vacuous', 'adj.', '空洞的', 'empty', 'Her vacuous smile annoyed him.', '她空洞的微笑惹他烦。', '9'],
  ['vainglorious', 'adj.', '虚荣的', 'vain', 'The vainglorious man boasted.', '虚荣的人自夸。', '9'],
  ['verisimilitude', 'n.', '逼真', 'realism', 'The film had verisimilitude.', '影片很逼真。', '9'],
  ['vestige', 'n.', '痕迹', 'trace', 'No vestige remained.', '没留下任何痕迹。', '9'],
  ['vicissitude', 'n.', '变迁', 'change', 'The vicissitude of life humbled him.', '人生的变迁让他谦卑。', '9'],
  ['vituperate', 'v.', '斥责', 'to abuse', 'He vituperated the foe.', '他痛斥敌人。', '9'],
  ['vociferous', 'adj.', '大声疾呼的', 'loud', 'The vociferous crowd cheered.', '大声疾呼的人群欢呼。', '9'],
  ['voracious', 'adj.', '贪吃的；渴求的', 'greedy', 'He is a voracious reader.', '他是个贪婪的读者。', '9'],
  ['winsome', 'adj.', '讨人喜欢的', 'charming', 'Her winsome smile charmed all.', '她讨喜的微笑迷住众人。', '9'],
  ['zeitgeist', 'n.', '时代精神', 'spirit of the age', 'The art captured the zeitgeist.', '艺术捕捉了时代精神。', '9'],
];

const lines = extra.map((e) => e.join(','));
appendFileSync(P, (lines.join('\n')) + '\n', 'utf8');
console.log('Appended ' + extra.length + ' band9 entries.');
